import '@fortawesome/fontawesome-free/css/all.min.css';
import { AntdRegistry } from '@ant-design/nextjs-registry';

import QueryProvider from '@/components/QueryProvider';
import './globals.css';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <QueryProvider>
          <AntdRegistry>{children}</AntdRegistry>
        </QueryProvider>
      </body>
    </html>
  );
}
